language: python

sudo: required
services:
  - docker

python:
  - "3.6"
  - "3.7-dev"

before_install:
  - sudo apt-get install -y docker-io docker-compose
  - sudo apt-get install -y npm

install:
  - make firstrun
