env:
  global:
    - secure: "YCAlFn1wM9WUa7Ub/Yi6+oZQ3QFDCUodSO4n8lVrbfFC1o0avDjCgE9oYrSVWQAeJHJbgzmQ71wg4PxVdFpZ6HLb/izfBc/7XFCN7CkmfikGwn40bkhLIfFwQFBy1KRby6LWoCmtMIfJPNFATR0n0yCSpuz0NhgyxDeM0BjLX4guTNonJiHXgj3yPD2Dm1VplYC3EWy4+DlVnM/D7mcCBvUhkE6lYz1y4kQ359lnapbzPsl6vMLYERRzbmyLjEAoIjjI/8x+KpmKhusuDymcK2paQvgAPMKga7k9A3fR/r75wWdeqNaXQi1/uC6fYXX28BEHYaGTqTPrlfb5hsBSRsepu+Dv7DKqovu3fgVed7qwj/JSS4nGuvx7/CHy1wMJkJkG7g+dphRMhrxs/sJCRINAM1a8y5hWG843+GDqzksrUpqdfjTt6bo1EnzqwWU+alzJoH80+yMy5+Z26e5080ti2V8G6Z1xLvHzdp8eg+EdO1y8n7hsxFlnlNUxGi7uwJ/fACoVr1lu0cDE7yG2hpY6BqZ2Ya+bN/KgFwDT+A1wXnFvf9J24HQ+S79CxuE+yX/cZc0m08ry8Zr0Xh4X2rE8r/P8Fr21LNOp3Uz2jEC4y5nMmowT7LPzvlcCkPfeObzy02aUpfIULxHDhl6WqP0015nQS57LczxYm5+6qwI="

language: python

sudo: required
services:
  - docker

python:
  - "3.7-dev"

before_install:
  - docker --version
  - docker-compose --version
  - pip3 install -r requirements.txt

install:
  - make build

script:
  - make test
