language: python

sudo: required
services:
  - docker

python:
  - "3.6"
  - "3.7-dev"

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker --version
  - docker-compose --version
  - sudo apt-get install -y npm
  # BATS for bash testing
  - git clone https://github.com/sstephenson/bats.git
  - export PATH="bats/bin:$PATH"

install:
  - make firstrun

script:
  # Same as `make run`, but with -d at the end to make it exit when all have been started
  - docker-compose up -d
  - bats tests/bats/

cache:
  timeout: 600
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
