language: python

sudo: required
services:
  - docker

python:
  - "3.6"
  - "3.7-dev"

before_install:
  - docker --version
  - docker-compose --version
  - sudo apt-get install -y npm

install:
  - make firstrun
