language: python

sudo: required
services:
  - docker

python:
  - "3.7-dev"

before_install:
  - docker --version
  - docker-compose --version
  - pip3 install -r requirements.txt

install:
  - make build

script:
  - make test
