version: "3"

services:

  backend:
    environment:
      HOST_FRONTEND: 'http://admin'
      HOST_BACKEND: 'http://api'
      HOST_PUBLIC: 'http://public'

  public:
    environment:
      HOST_BACKEND: 'http://api'
      
  admin:
    environment:
      HOST_BACKEND: 'http://api'

  servicebase:
    command: ["/bin/sleep", "3600"]

  library:
    command: ["/bin/sleep", "3600"]

  selenium:
    image: selenium/standalone-chrome-debug
    networks:
      - makeradmin
    ports:
      - '4444'
    volumes:
      - /dev/shm:/dev/shm

  email-dispatcher:
    environment:
      MAILGUN_DOMAIN: ""
      MAILGUN_KEY: ""
      
  test:
    image: makeradmin/test:1.0
    build:
      context: ./api
      dockerfile: TestDockerfile
    networks:
      - makeradmin
    command:
      - "/work/test_run.sh"
    volumes:
      - .test:/work/.test
    depends_on:
      - admin
      - public
      - api
      - selenium
    environment:
      WEBDRIVER_TYPE: "REMOTE_CHROME"
      API_BEARER:
      HOST_FRONTEND: 'http://admin'
      HOST_BACKEND: 'http://api'
      HOST_PUBLIC: 'http://public'
      APIGATEWAY: "api"
      STRIPE_PRIVATE_KEY:
      STRIPE_PUBLIC_KEY:
      TEST_PARALELLISM:
      SELENIUM_BASE_TIMEOUT:
      SELENIUM_SCREENSHOT_DIR: "/work/.test/selenium-screenshots"
      
