version: "3"

services:
  db2:
    ports:
      - "3306:3306"

  # TODO BM Remove
  # api-gateway:
  #   volumes:
  #     - ./apigateway/lumen/routes:/var/www/html/routes
  #     - ./apigateway/lumen/app:/var/www/html/app
  #     - ./test/src/Makeradmin:/var/www/html/test
  #   ports:
  #     - "8010:80"
  #   environment:
  #     APP_DEBUG: "true"

  api:
    volumes:
      - ./api/src:/work/src
    ports:
      - "8010:80"
    environment:
      APP_DEBUG: "true"
      
  membership:
    volumes:
      - ./membership/lumen/routes:/var/www/html/routes
      - ./membership/lumen/app:/var/www/html/app
      - ./test/src/Makeradmin:/var/www/html/test

  messages:
    volumes:
      - ./messages/lumen/routes:/var/www/html/routes
      - ./messages/lumen/app:/var/www/html/app
      - ./test/src/Makeradmin:/var/www/html/test

  email-dispatcher:
    volumes:
      - ./emaildispatcher/lumen/routes:/var/www/html/routes
      - ./emaildispatcher/lumen/app:/var/www/html/app
      - ./test/src/Makeradmin:/var/www/html/test

  multiaccesssync:
    volumes:
      - ./data/multiaccess-uploads:/var/www/html/storage/uploads
      - ./multiaccesssync/lumen/routes:/var/www/html/routes
      - ./multiaccesssync/lumen/app:/var/www/html/app
      - ./test/src/Makeradmin:/var/www/html/test

  backend:
    volumes:
      - ./backend/src:/work/src
    environment:
      APP_DEBUG: "true"
      
  public:
    ports:
      - "8011:80"
    volumes:
      - ./public/ts:/work/ts
      - ./public/scss:/work/scss
      - ./public/src:/work/src
    environment:
      APP_DEBUG: "true"
      
  admin:
    ports:
      - "8009:80"
    environment:
      APP_DEBUG: "true"
