version: "3"

services:

  api-gateway:
    ports:
      - "9010:80"
      
  public:
    ports:
      - "9011:80"
      
  admin:
    ports:
      - "9009:80"

  servicebase:
    command: ["/bin/sleep", "3600"]

  library:
    command: ["/bin/sleep", "3600"]

  selenium:
    image: selenium/standalone-chrome-debug
    networks:
      - makeradmin
    ports:
      - '4444'
    volumes:
      - /dev/shm:/dev/shm
  
  test:
    image: makeradmin/test:1.0
    build:
      context: ./test
    networks:
      - makeradmin
    command:
      - "/work/run.sh"
    depends_on:
      - admin
      - public
      - api-gateway
      - selenium
    environment:
      WEBDRIVER_TYPE: "REMOTE_CHROME"
      TEST_MODE: "DOCKER"
      API_BEARER: "${API_BEARER}"
      HOST_BACKEND: "http://api-gateway:80"
      STRIPE_PRIVATE_KEY: "${STRIPE_PRIVATE_KEY}"
      STRIPE_PUBLIC_KEY: "${STRIPE_PUBLIC_KEY}"
      SELENIUM_TIMEOUT: "${SELENIUM_TIMEOUT}"
      SKIP_SELENIUM_TESTS: "${SKIP_SELENIUM_TESTS}"

