version: "3"

services:
  db2:
    ports:
      - "3306:3306"

  api:
    volumes:
      - ./api/src:/work/src
      - logs:/work/logs
    ports:
      - "8010:80"
    environment:
      APP_DEBUG: "true"
      
  membership:
    volumes:
      - ./membership/lumen/routes:/var/www/html/routes
      - ./membership/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library

  messages:
    volumes:
      - ./messages/lumen/routes:/var/www/html/routes
      - ./messages/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library

  email-dispatcher:
    volumes:
      - ./emaildispatcher/lumen/routes:/var/www/html/routes
      - ./emaildispatcher/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library

  multiaccesssync:
    volumes:
      - ./data/multiaccess-uploads:/var/www/html/storage/uploads
      - ./multiaccesssync/lumen/routes:/var/www/html/routes
      - ./multiaccesssync/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library

  backend:
    volumes:
      - ./backend/src:/work/src
    environment:
      APP_DEBUG: "true"
      
  public:
    ports:
      - "8011:80"
    volumes:
      - ./public/ts:/work/ts
      - ./public/scss:/work/scss
      - ./public/src:/work/src
    environment:
      APP_DEBUG: "true"
      
  admin:
    ports:
      - "8009:80"
    environment:
      APP_DEBUG: "true"

volumes:
  logs: