version: "2"
services:
  db2:
    image: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
      - ./logs/mysql:/var/www/html/storage/logs
    environment:
      # Note: the config only seems to be updated when the container is initially created
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_ROOT_HOST: "db2"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - makeradmin

  api-gateway:
    image: makeradmin/apigateway:1.0
    container_name: makeradmin-apigateway
    build: ./MakerAdmin-ApiGateway
    volumes:
      - ./logs/apigateway:/var/www/html/storage/logs
    depends_on:
      - db2
    ports:
      - "8010:80"
    networks:
      - makeradmin
    environment:
        APP_DEBUG: "true"
        MYSQL_HOST: "db2:${MYSQL_PORT}"
        MYSQL_DB: "${MYSQL_DB}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASS: "${MYSQL_PASS}"
        BEARER: "${API_BEARER}"

  economy:
    image: makeradmin/economy:1.0
    container_name: makeradmin-economy
    build: ./MakerAdmin-Economy
    volumes:
      - ./logs/economy:/var/www/html/storage/logs
      - ./data/economy-vouchers:/var/www/html/vouchers
    environment:
        MYSQL_HOST: "db2:${MYSQL_PORT}"
        MYSQL_DB: "${MYSQL_DB}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASS: "${MYSQL_PASS}"
        APIGATEWAY: "api-gateway"
        BEARER: "${API_BEARER}"
    depends_on:
      - api-gateway
    networks:
      - makeradmin

  membership:
    image: makeradmin/membership:1.0
    container_name: makeradmin-membership
    build: ./MakerAdmin-Membership
    volumes:
      - ./logs/membership:/var/www/html/storage/logs
    environment:
        MYSQL_HOST: "db2:${MYSQL_PORT}"
        MYSQL_DB: "${MYSQL_DB}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASS: "${MYSQL_PASS}"
        APIGATEWAY: "api-gateway"
        BEARER: "${API_BEARER}"
    depends_on:
      - api-gateway
    networks:
      - makeradmin

  messages:
    image: makeradmin/messages:1.0
    container_name: makeradmin-messages
    build: ./MakerAdmin-Messages
    volumes:
      - ./logs/messages:/var/www/html/storage/logs
    environment:
        MYSQL_HOST: "db2:${MYSQL_PORT}"
        MYSQL_DB: "${MYSQL_DB}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASS: "${MYSQL_PASS}"
        APIGATEWAY: "api-gateway"
        BEARER: "${API_BEARER}"
    depends_on:
      - api-gateway
    networks:
      - makeradmin

  sales:
    image: makeradmin/sales:1.0
    container_name: makeradmin-sales
    build: ./MakerAdmin-Sales
    volumes:
      - ./logs/sales:/var/www/html/storage/logs
    environment:
        MYSQL_HOST: "db2:${MYSQL_PORT}"
        MYSQL_DB: "${MYSQL_DB}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASS: "${MYSQL_PASS}"
        APIGATEWAY: "api-gateway"
        BEARER: "${API_BEARER}"
    depends_on:
      - api-gateway
    networks:
      - makeradmin

  frontend:
    image: makeradmin/frontend:1.0
    container_name: makeradmin-frontend
    build: ./MakerAdmin-Frontend
    ports:
      - "8009:80"
    depends_on:
      - economy
      - membership
      - messages
      - sales
    networks:
      - makeradmin

networks:
  makeradmin:
volumes:
  dbdata:
