name: Check formatting of source code

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install --user ruff
    - name: Check formatting
      run: |
        ruff format --diff
    - name: Inform about how to fix failure
      if: failure()
      run: |
        echo '::notice::To auto-fix the formatting error, run `make format`'